version: "3.9"

services:
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  rag-app:
    build: .
    container_name: rag-app
    ports:
      - "8000:8000"
    volumes:
      - chroma:/app/db
    depends_on:
      - ollama-server

volumes:
  ollama:
  chroma:
